"""
Skill: Auto Playlist
─────────────────────
Crea playlists automáticamente en MongoDB según criterios del usuario:
géneros, artistas, canciones no escuchadas, etc.
"""
import re
import random
from datetime import datetime
from motor.motor_asyncio import AsyncIOMotorDatabase
from bson import ObjectId


async def create_auto_playlist(
    db: AsyncIOMotorDatabase,
    user_id: str,
    name: str,
    criteria: dict,
    recent_song_ids: list = None,
) -> dict:
    """
    Crea una playlist automática y la guarda en Mongo.

    criteria ejemplo:
    {
        "genre":        "Rock",
        "artist":       null,
        "unheard_only": true,
        "limit":        20
    }
    """
    songs_col    = db["musics"]
    playlist_col = db["playlists"]

    limit        = min(criteria.get("limit", 20), 50)
    genre        = criteria.get("genre")
    artist       = criteria.get("artist")
    unheard_only = criteria.get("unheard_only", False)

    # Construir filtro
    filters: dict = {
        "status": {"$regex": r"^\s*complete\s*$", "$options": "i"},
    }

    or_clauses = []
    if genre:
        or_clauses.append({"genre": re.compile(re.escape(genre), re.IGNORECASE)})
    if artist:
        or_clauses.append({"artist": re.compile(re.escape(artist), re.IGNORECASE)})
    if or_clauses:
        filters["$or"] = or_clauses

    # Excluir canciones ya escuchadas si se pidió
    if unheard_only and recent_song_ids:
        exc = []
        for sid in recent_song_ids:
            try:
                exc.append(ObjectId(str(sid)))
            except Exception:
                pass
        if exc:
            filters["_id"] = {"$nin": exc}

    cursor = songs_col.find(filters, {"_id": 1}).limit(limit * 2)
    candidates = await cursor.to_list(length=limit * 2)
    random.shuffle(candidates)
    selected_ids = [doc["_id"] for doc in candidates[:limit]]

    playlist_doc = {
        "userId":        user_id,
        "name":          name,
        "isPublic":      False,
        "songs":         selected_ids,
        "autoGenerated": True,
        "criteria":      criteria,
        "createdAt":     datetime.utcnow(),
        "updatedAt":     datetime.utcnow(),
    }

    result = await playlist_col.insert_one(playlist_doc)
    return {
        "ok":      True,
        "playlist": {
            "_id":   str(result.inserted_id),
            "name":  name,
            "songs": [str(s) for s in selected_ids],
            "count": len(selected_ids),
        },
    }